#Basic image.
#Note you will need to get your own volume mount users and groups
#to add your own sciclone drives - the below comments out
#these parts, as you will be unable to authenticate.
apiVersion: v1
kind: Pod
metadata:
  name: geolab-generic
spec:
  restartPolicy: Always
  #volumes:
  #  - name: geograd
  #    nfs:
  #      server: 128.239.56.166
  #      path: /sciclone/geograd
  #securityContext:
  #      runAsUser: 71032
  #      runAsGroup: 9915
  containers:
    - name: conda-container
      image: "ghcr.io/d8a-science/pytorch-cuda:latest"
  #    volumeMounts:
  #      - name: geograd
  #        mountPath: /sciclone/geograd/
      resources:
        limits:
          cpu: 8
          nvidia.com/gpu: 2
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Double check the mount worked:"
          ls /sciclone/geograd
          echo "Sleeping indefinitely..."
          sleep infinity