apiVersion: v1
kind: Pod
metadata:
  name: filestore
spec:
  restartPolicy: Always
  volumes:
    - name: home-volume
      persistentVolumeClaim:
        claimName: dsmillerrunfol-rwm
  containers:
    - name: conda-container
      image: "ghcr.io/d8a-science/pytorch-cuda:latest"
      volumeMounts:
        - name: geograd
          mountPath: /sciclone/geograd/
      resources:
        limits:
          cpu: 8
          nvidia.com/gpu: 2
      securityContext:
        runAsUser: 82656
      volumes:
        - name: geograd
          nfs:
            server: 128.239.56.166
            path: /sciclone/geograd
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Disk space usage for /kube/home volume:"
          df -h /sciclone/geograd
          echo "Sleeping indefinitely..."
          sleep infinity