apiVersion: v1
kind: Pod
metadata:
  name: geolab-generic
spec:
  restartPolicy: Always
  volumes:
    - name: geograd
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd
  securityContext:
        runAsUser: 71032
        runAsGroup: 9915
  containers:
    - name: conda-container
      image: "ghcr.io/d8a-science/pytorch-cuda:latest"
      imagePullPolicy: Always
      volumeMounts:
        - name: geograd
          mountPath: /sciclone/geograd/
      resources:
        limits:
          cpu: 8
          nvidia.com/gpu: 2
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Double check the mount worked:"
          ls /sciclone/geograd
          echo "Sleeping indefinitely..."
          sleep infinity